# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            赵一好的技术博客
tagline:          'A Jekyll theme'
description:      '恐惧只能使自己盲目<br />盲目只能夸大魔鬼的狰狞嘴脸<br />也许我的样子比它们更可怕<br />当我以命相拼<br />一往无前<br />只要我还有一根完整的龙骨<br />绝不驶进避风的港湾<br />把生命放在征途上<br />让勇敢来决定道路的宽窄、长短<br /> -- 白桦的诗《船》'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/cnnqjban

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Demo233/Demo233.github.io
